version: '3'
services:
  app:
    restart: unless-stopped
    build: .
    image: dingsj101/course_select_system:1.3
    ports:
     - "8000:8000"
    volumes:
     - .:/course_select_system
     - /etc/localtime:/etc/localtime
    container_name: "course_select_system"
    command: ["sh", "run.sh"]
  